// Generated by CoffeeScript 1.6.3
(function() {
  var SELECTOR_LIMIT, bless, css, newAst;

  css = require('css');

  SELECTOR_LIMIT = 4095;

  newAst = function(rules) {
    return {
      type: 'stylesheet',
      stylesheet: {
        rules: rules
      }
    };
  };

  bless = function(data) {
    var ast, nestedRule, newAsts, newData, numSelectors, rule, rulesCache, totalNumSelectors, _i, _j, _len, _len1, _ref, _ref1;
    ast = css.parse(data);
    numSelectors = 0;
    totalNumSelectors = 0;
    rulesCache = [];
    newAsts = [];
    _ref = ast.stylesheet.rules;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      rule = _ref[_i];
      switch (rule.type) {
        case 'rule':
          numSelectors += rule.selectors.length;
          totalNumSelectors += rule.selectors.length;
          break;
        default:
          _ref1 = rule.rules;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            nestedRule = _ref1[_j];
            numSelectors += nestedRule.selectors.length;
            totalNumSelectors += nestedRule.selectors.length;
          }
      }
      rulesCache.push(rule);
      if (numSelectors === SELECTOR_LIMIT) {
        newAsts.push(newAst(rulesCache));
        rulesCache = [];
        numSelectors = 0;
      }
    }
    if (rulesCache.length) {
      newAsts.push(newAst(rulesCache));
    }
    newData = (function() {
      var _k, _len2, _results;
      _results = [];
      for (_k = 0, _len2 = newAsts.length; _k < _len2; _k++) {
        ast = newAsts[_k];
        _results.push(css.stringify(ast));
      }
      return _results;
    })();
    return {
      data: newData,
      numSelectors: totalNumSelectors
    };
  };

  module.exports = bless;

}).call(this);
