// Generated by CoffeeScript 1.6.3
(function() {
  var bless, colors, fs, input, output, path, pjson, program;

  colors = require('colors');

  fs = require('fs');

  path = require('path');

  pjson = require(path.join(__dirname, '..', 'package.json'));

  program = require('commander');

  bless = require(path.join(__dirname, '..', 'lib', 'bless'));

  program.version(pjson.version).usage('<input file> [<output file>] [options]').option('-f, --force', 'modify the input file provided'.yellow).parse(process.argv);

  input = program.args[0];

  if (!input) {
    console.log('blessc: no input provided'.red);
    process.exit(1);
  }

  if (input !== '-' && !/\.css$/.test(input)) {
    console.log('blessc: input file is not a .css file'.red);
    process.exit(1);
  }

  output = program.args[1];

  output = output || input;

  if (output === '-') {
    console.log('blessc: no output file provided'.red);
    process.exit(1);
  }

  if (output === input && !program.force) {
    console.log('blessc: use --force or -f to modify the input file'.red);
    process.exit(1);
  }

  fs.readFile(input, 'utf8', function(err, data) {
    var filesData;
    if (err) {
      throw err;
    }
    return filesData = bless(data);
  });

}).call(this);
