// Generated by CoffeeScript 1.7.1
(function() {
  var importer, path;

  path = require("path");

  importer = function(options) {
    var dirname, extension, filename, imports, index, item, numFiles, output, statements, suffix, _i;
    output = options.output, suffix = options.suffix, numFiles = options.numFiles;
    if (numFiles <= 1) {
      return "";
    }
    imports = [];
    for (index = _i = 1; 1 <= numFiles ? _i < numFiles : _i > numFiles; index = 1 <= numFiles ? ++_i : --_i) {
      dirname = path.dirname(output);
      extension = path.extname(output);
      filename = path.basename(output, extension);
      imports.push("./" + filename + "-" + suffix + "-" + index + extension);
    }
    statements = (function() {
      var _j, _len, _results;
      _results = [];
      for (_j = 0, _len = imports.length; _j < _len; _j++) {
        item = imports[_j];
        _results.push("@import(\"" + item + "\");");
      }
      return _results;
    })();
    return statements.join("\n");
  };

  module.exports = importer;

}).call(this);
